import { createApp } from 'vue'
import App from './App.vue'
import '@/assets/tailwind.css'
import '@fontsource/noto-sans/400.css'
import '@fontsource/inter/400.css'
import '@fontsource/noto-serif/400.css'
import '@fontsource/noto-sans-jp/400.css'
import '@fontsource/noto-serif-jp/400.css'
import '@fontsource/jetbrains-mono/400.css'
import '@fontsource/noto-sans-kr/400.css'
import '@fontsource/noto-serif-kr/400.css'
import '@fontsource/noto-sans-sc/400.css'
import '@fontsource/noto-sans-tc/400.css'
import '@fontsource/noto-sans-arabic/400.css'
import '@fontsource/noto-naskh-arabic/400.css'
import '@fontsource/noto-sans-devanagari/400.css'
import '@fontsource/noto-sans-hebrew/400.css'

createApp(App).mount('#app')
