/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./entrypoints/**/*.{html,ts,js,vue}', './components/**/*.{vue,ts}'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'ui-sans-serif',
          '-apple-system',
          'system-ui',
          '"Segoe UI"',
          'Helvetica',
          '"Apple Color Emoji"',
          'Arial',
          'sans-serif',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          '"SF Mono"',
          'Menlo',
          'Consolas',
          '"Liberation Mono"',
          'monospace',
        ],
      },
      colors: {
        bg_primary: 'var(--bg_primary)',
        bg_secondary: 'var(--bg_secondary)',
        bg_blockquote: 'var(--bg_blockquote)',
        bg_active: 'var(--bg_active)',
        bg_delete: 'var(--bg_delete)',
        bg_button_primary: 'var(--bg_button_primary)',
        border_primary: 'var(--border_primary)',
        border_blockquote: 'var(--border_blockquote)',
        icon_primary: 'var(--icon_primary)',
        text_primary: 'var(--text_primary)',
        text_button_primary: 'var(--text_button_primary)',
        text_link: 'var(--text_link)',
      },
      fontSize: {
        h1: ['30px', { lineHeight: '1.75' }],
        h2: ['27px', { lineHeight: '1.75' }],
        h3: ['24px', { lineHeight: '1.75' }],
        h4: ['21px', { lineHeight: '1.75' }],
        h5: ['19.5px', { lineHeight: '1.75' }],
        h6: ['18px', { lineHeight: '1.75' }],
        body: ['16px', { lineHeight: '1.6' }],
        small: ['14px', { lineHeight: '1.75' }],
      },
    },
  },
  plugins: [],
}
